name: Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v1.1
      with:
        xcode-version: '11.3.1'
    - run: brew bundle
    - run: bundle install --deployment
    - run: xcodebuild -workspace EPUBViewer.xcworkspace -scheme EPUBViewer -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3' test > >(xcpretty -f `bundle exec xcpretty-actions-formatter`)
