name: Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - uses: sinoru/actions-setup-xcode@v1.1
      with:
        xcode-version: '11.3.1'
    - run: brew bundle
    - run: bundle install --deployment
    - run: xcodebuild -workspace EPUBViewer.xcworkspace -scheme EPUBViewer -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3' test > >(xcpretty -f `bundle exec xcpretty-actions-formatter`)
